
Section "ServerLayout"
  Identifier "XRDP GPU Server"
  Screen 0 "dGPU"
  InputDevice "xrdpMouse" "CorePointer"
  InputDevice "xrdpKeyboard" "CoreKeyboard"
EndSection

Section "ServerFlags"
  # This line prevents "ServerLayout" sections in xorg.conf.d files
  # overriding the "XRDP GPU Server" layout (xrdp #1784)
  Option "DefaultServerLayout" "XRDP GPU Server"
  Option "DontVTSwitch" "on"
  Option "AutoAddDevices" "off"
  Option "AutoAddGPU" "off"
EndSection

# This section might be needed if the nvidia Xorg module is not installed
# in the default modules directory ie /usr/lib/xorg/modules
# example package on ubuntu xserver-xorg-video-nvidia-535
#Section "Files"
#    ModulePath "/usr/lib/x86_64-linux-gnu/nvidia/xorg,/usr/lib/xorg/modules"
#EndSection

Section "Module"
  Load "xorgxrdp"
EndSection

Section "InputDevice"
  Identifier "xrdpKeyboard"
  Driver "xrdpkeyb"
EndSection

Section "InputDevice"
  Identifier "xrdpMouse"
  Driver "xrdpmouse"
EndSection

Section "Screen"
  Identifier "dGPU"
  Device "dGPU"
  Option "DPI" "96 x 96"
EndSection

Section "Device"
  Identifier "dGPU"
  Driver "nvidia"
  Option "UseDisplayDevice" "none"
  Option "ConnectToAcpid" "false"
  BusID "PCI:3:0:0"
EndSection
